### ISSUE TITLE
Renegotiating doesn't complete

### ISSUE THREAD

**Issue by amirmc** [mirleft/ocaml-tls#140]
Safari on iOS 7.1.1

Still spinning and nothing has happened. Reloading the page worked.

**Comment by hannesm** [comment]
there's another mail thread on the tls working group about this problem: https://mailarchive.ietf.org/arch/search/?email_list=tls&q=Application+data+during+renegotiation+handshake -- my opinion is we should move towards blocking during renegotiation (also, in current master renegotiation is off by default) to prevent situations where the application does not know whether data was received before or after the renegotiation.  I'll prepare a PR for this soon.
