### ISSUE TITLE
non-exhaustiv pattern matches

### ISSUE THREAD

**Issue by avsm** [mirleft/ocaml-tls#221]
```
File "lib/writer.ml", line 126, characters 17-708:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
(MaxFragmentLength _|UnknownExtension _)
File "lib/writer.ml", line 246, characters 4-495:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
CertificateRequest _
```

**Comment by hannesm** [comment]
yes... unfinished portions - which are partially due to unfinished features (notably client_auth branch...)... will hopefully be more complete by the end of the month

**Comment by hannesm** [comment]
update on this: there are still some non-exhaustive pattern matches in the codebase - but this being printer (not intended to be used apart from for debugging) and writer (when trying to write extensions we never generate inside of the stack)

especially, HEARTBEAT packets are handled now (get an unexpected_message alert back), and the missing certificaterequest/verify reader/writer have been added when client_auth branch was merged.

@avsm please close if you're convinced (yes, there needs to be a cleanup of tls such that it nicely compiles without warnings). but there is no harm anymore by non-exhaustive pattern matches...

**Comment by hannesm** [comment]
closing because the one `HEARTBEAT` case has been fixed, and the others are left as is now (there is nothing inside of OCaml-TLS calling these with the mentioned patterns anyways).. (yes, this is still slightly annoying and will need to be fixed at some point)
