### ISSUE TITLE
XSS via Request data (user agent, for example)

### ISSUE THREAD

**Issue by craSH** [mirleft/ocaml-tls#226]
A user requesting a page with a malicious user agent can cause a Cross-Site Scripting vulnerability via HTML/Javascript injection. While this is a bit of a contrived scenario, the input should still be properly encoded prior to being displayed on the page, along with any other user-supplied input.

Example client user-agent that causes the issue to trigger:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:27.0) Gecko/20100101 Firefox/27.0'"><script>alert("UA XSS")</script><div id="'
```

This should trigger whenever the user then clicks the ```ApplicationData``` item, as that renders the request headers, including the **User-Agent** and it's value.

**Comment by pqwy** [comment]
Assuming you are talking about the [demo server](https://tls.openmirage.org/) here;

I can see how a user could hurt themselves. They could cause our server to send them back arbitrary javascript that they sent to our server, thereby causing arbitrary code of their choice to run in their browser.

But pray tell, when they finally tire of watching the alert pop up, how could a malicious user affect someone *else* this way?

**Comment by craSH** [comment]
Indeed, that's why I say it's contrived, and maybe I should have just said it's HTML/JS injection vs. XSS.
Since the demo server doesn't seem to show data from any other users, I can't think of a cross-user attack scenario in this case.

**Comment by hannesm** [comment]
@craSH thanks for the report - and as you mentioned, the server does not show data from any other users... (repository is at https://github.com/mirleft/tls-demo-server).. I'll close this issue (please reopen if you disagree)
