### ISSUE TITLE
intermediate certificates errors

### ISSUE THREAD

**Issue by avsm** [mirleft/ocaml-tls#245]
I have a Gandi SSL cert with an intermediate cert, but it doesn't seem to be picked up by some of the SSL checkers for some reason (but my browsers all connect fine).  What's the right way to get an intermediate cert added to my domain crt?  I have currently appended them together via `cat` in the `.crt` file as I do with OpenSSL.

e.g.
https://www.sslshopper.com/ssl-checker.html#hostname=signpost.io

**Comment by hannesm** [comment]
what your server is presenting are two certificates:
````
 0 s:/OU=Domain Control Validated/OU=Gandi Standard Wildcard SSL/CN=*.signpost.io
   i:/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
 1 s:/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
   i:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
````

What (at least my browser) is doing: completing the chain with `USERTrust RSA Certificate Authority` (which signed Gandi), `AddTrust External CA Root` (which signed USERTrust RSA CA), `UTN - DATACorp SGC` (which signed AddTrust External CA Root) - which is a self-signed certificate and one of my trust anchors.

Some SSL checkers might not have those additional intermediate certificates available in their trust chain... what you can do is grabbing their certificates as well and transmitting them over the wire -- thus a client only needs to have the `UTN - DATACorg SGC` certificate.

**Comment by hannesm** [comment]
there's nothing we can do about it - you can choose to (download and) configure that the remaining intermediate certificates are presented during the TLS handshake -- but this will increase the data which needs to be sent... or bug sslshopper.com to include `USERTrust RSA Certification Authority` as trust anchor...
