### ISSUE TITLE
Host jquery, Raphaël and Underscore locally

### ISSUE THREAD

**Issue by onitake** [mirleft/ocaml-tls#263]
It's become a widespread (mis)practice to host JavaScript on external content delivery networks, despite the implied security risks.

JavaScript source files normally contribute very little to page loading times, bandwidth and server load, so the usual arguments for hosting them externally are weak. In contrast, the risk of third party information sharing and code injection is very high. This is obviously a matter of trust, but developers should not simply forego user's concerns about the trustworthiness of Google, Cloudflare, et al.

This should be of particular importance to a project that concerns itself with data transmission security.

**Comment by dbuenzli** [comment]
This should be filed here https://github.com/mirleft/tls-demo-server

**Comment by onitake** [comment]
I'd love to, but the github issues section is not enabled there.

**Comment by hannesm** [comment]
@onitake I just enabled GitHub issues on the tls-demo-server repository.

While I'm in general in your favour (of not using CDNs, for containment and privacy issues - which tls-demo-server also did initally), I don't really see the security risk here: if you accept arbitrary JavaScript from some server on the internet, you're screwed. OTOH, a browser is much more likely to have cached the file if using an external CDN. And I cannot see any privacy impact of people browsing https://tls.openmirage.org

Feel free to open an issue at the tls-demo-server repository if you have a more concrete concern.
