### ISSUE TITLE
Having ocaml-tls linked breaks daemonizing code

### ISSUE THREAD

**Issue by smondet** [mirleft/ocaml-tls#302]
Quite strange: just installing `tls` breaks lwt-applications that daemonize themselves
(e.g. the code
[here](https://github.com/hammerlab/ketrew/blob/3ec843d98e85f6d44ed3efde77363ce2fb3d5640/src/lib/command_line.ml#L480)).
The daemonized process hangs at the first `Lwt_io` call that happens
(even without using `CONDUIT_TLS=native`, or before doing any network call at all).

This commit seems suspicious:
https://github.com/mirleft/ocaml-tls/commit/7e5b5c3e189d121b173dcb1fa1b3a30055853383
It calls initialization code at module-loading time.
(which is general bad practice anyways).

Running non-trivial Lwt-code can break processes that use Lwt while daemonizing.
Cf. also the comments of https://github.com/ocsigen/lwt/issues/82

I tried to remove some of the load-time calls but it didn't work, only `opam
remove nocrypto` fixes/hides the issue.

``` diff
diff --git a/lwt/tls_lwt.ml b/lwt/tls_lwt.ml
index 8567e9c..d352597 100644
--- a/lwt/tls_lwt.ml
+++ b/lwt/tls_lwt.ml
@@ -248,4 +248,6 @@ and connect ?trace authenticator addr =


 (* Boot the entropy loop at module init time. *)
+  (*
 let () = ignore @@ Nocrypto_entropy_lwt.initialize ()
+*)
```

``` diff
diff --git a/lwt/nocrypto_entropy_lwt.ml b/lwt/nocrypto_entropy_lwt.ml
index e848cdf..1ccc377 100644
--- a/lwt/nocrypto_entropy_lwt.ml
+++ b/lwt/nocrypto_entropy_lwt.ml
@@ -47,12 +47,13 @@ let stop t =
   catch (fun () -> Lwt_unix.close t.fd)
     Unix.(function Unix_error (EBADF, _, _) -> return_unit | exn -> fail exn)

-let active = Lwt_mvar.create None
+let active () = Lwt_mvar.create None

 let initialize () =
+    Printf.eprintf "\nentropy_lwt.init !!\n\n%!";
   Nocrypto_entropy_unix.initialize () ;
   let g = !Rng.generator in
-  mvar_map active @@ function
+  mvar_map (active ()) @@ function
     | Some t when t.g == g -> return (Some t)
     | Some t               -> stop t >>= fun () -> attach ~period g >|= some
     | None                 -> attach ~period g >|= some
```

``` diff
diff --git a/lib/conduit_lwt_tls.ml b/lib/conduit_lwt_tls.ml
index f4a2bdc..1a14157 100644
--- a/lib/conduit_lwt_tls.ml
+++ b/lib/conduit_lwt_tls.ml
@@ -17,8 +17,9 @@

 open Lwt

+(*
 let _ = Nocrypto_entropy_lwt.initialize ()
-
+*)
 let with_socket sockaddr f =
   let fd = Lwt_unix.socket (Unix.domain_of_sockaddr sockaddr) Unix.SOCK_STREAM 0 in
   Lwt.catch (fun () -> f fd) (fun e ->

```

PS: in my Lwt Vs nqsb-tls adventures, I had also this issue: https://github.com/mirage/ocaml-conduit/issues/97.

**Comment by hannesm** [comment]
this is strange. could you try to minimise the test case, and link to a complete one here? does it depend on the lwt version (and/or OCaml version, operating system)?

**Comment by smondet** [comment]
I tried with both Mac OSX and Linux-CentOS, latest OCaml, Lwt 2.4.8 (the server is https://github.com/hammerlab/ketrew).

I had had a very similar problem before → https://github.com/ocsigen/lwt/issues/82
and hence removed all the Lwt code that could happen before daemonizing.
It reappeared lately while trying ocaml-tls. 

I'll try to see if I manage to extract a minimal example.

**Comment by pqwy** [comment]
I can't repro with:

```
let () =
  Nocrypto_entropy_lwt.initialize ();
  Lwt_daemon.daemonize ~stdin:`Keep ~stdout:`Keep ();
  Lwt_main.run (Lwt_io.printf "desu.\n%!")
```

(Linked against `lwt.unix,nocrypto.lwt`.) Tried a few permutations of `initialize`, `daemonize` and `run`. It would help if you could come up with a minimal test case.

We used to offload entropy initialization to the client, and it proved to be horribly painful. I wouldn't put that kind of code in the init path otherwise, but the RNG is something special.

Completely unrelated to this issue in itself: I would advise against doing the Unix daemonization dance. It breaks modular service management. Stuff like `daemontools` just malfunctions, and `systemd` has special logic in place solely to defeat it by chasing forking processes via cgroups, in order to keep track of the main process.

**Comment by hannesm** [comment]
there hasn't been any activity for 3 years here, closing. Please reopen if this is still an issue for you (a minimal example would be great, so we can reproduce). I also agree with @pqwy that the Unix daemonization dance breaks service management.
