### ISSUE TITLE
extension ordering

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-tls#319]
there is no strict one defined, but (from https://bugzilla.mozilla.org/show_bug.cgi?id=1243641): `we have encountered a host of compatibility issues when an empty extension is the last extension`... seems easy to fix for us (if we have a mandatory non-empty extension, maybe securerenegotiation).  i somehow wish people would document this... hosts to test this (from mozillas bug): https://apps.reg.uga.edu https://appserver.lasalle.edu.co https://correo.uchile.cl https://grep.elasticpath.com https://mealapps.flaglerschools.com https://mypassword.cau.edu https://www.portaldefacturas.com https://www.sqlpower.ca

**Comment by cfcs** [comment]
How about adding documentations about things like this in the code?

**Comment by hannesm** [comment]
@cfcs there's no straightforward location to document this in the code atm, since client hello (and its extensions) are constructed at various places... I thought by marking it as interoperability in here, this is some sensible documentation... but yes, there should be somewhere (maybe not ocaml-tls specific) common TLS interop obstacles
