### ISSUE TITLE
opam failed with tls 0.7.0

### ISSUE THREAD

**Issue by dinosaure** [mirleft/ocaml-tls#326]
`tls` needs `cstruct.syntax` but the installation of `cstruct.2.0.0` don't provide this library :(

**Comment by hannesm** [comment]
hmm? could you elaborate a bit?

**Comment by dinosaure** [comment]
Sorry, it's my mistake, I press enter key :( ...

**Comment by hannesm** [comment]
tls-0.7.1 should work for you.. I added constraints in a PR to opam-repository: https://github.com/ocaml/opam-repository/pull/6383

**Comment by dinosaure** [comment]
Thanks, I doing this PR but you are faster than me :) !
