### ISSUE TITLE
Update certificate source

### ISSUE THREAD

**Issue by g2p** [mirleft/ocaml-tls#334]
Currently this is a bit messy.

There are three files:
- ca-root-nss.crt
- ca-root-nss-short.crt
- cacert.crt

CACert shouldn't be trusted, it has never been accepted by Mozilla and its purpose has been obsoleted by Let's Encrypt.

ca-root-nss.crt is a very old extraction from Mozilla's trusted set, and contains compromised authorities like CNNIC.
ca-root-nss-short.crt is the above, minus the readable version of the certificates, plus cacert.crt.

I recommend using the ca-certificates bundle from Android AOSP, which is a subset (about 9 removals so far) of Mozilla's certdata.txt reference bundle. The only minor downside (for the git log) is that the order will change.

It doesn't sound optimal to duplicate the list (otherwise everything is loaded twice), so I'd suggest keeping the readable version for easier maintenance. The shorter version can be extracted with sed: https://stackoverflow.com/questions/28895208/

**Comment by pqwy** [comment]
Bear in mind that `./certificates` is *not* used the library code. It's a dump of certificate-related material for examples and tests.

This project is not in the business of distributing CAs.

**Comment by g2p** [comment]
That's wise, but the certificates do ship when ocaml-tls is installed.
Maybe they shouldn't be installed, or they should be reduced to a few examples instead of a full set?

**Comment by hannesm** [comment]
closing this issue since they are no longer installed when installing ocaml-tls.  as mentioned in PR #335 there is likely need for a certificate library in OCaml (but this should not be bundled with TLS).
