### ISSUE TITLE
DTLS support?

### ISSUE THREAD

**Issue by jerome-arzel** [mirleft/ocaml-tls#344]
Is it easy to adapt ocaml-tls for DTLS? [RFC4347](https://tools.ietf.org/html/rfc4347)

**Comment by hannesm** [comment]
It should at least be doable.  What is your use case for DTLS?

The main difference AFAICS is that DTLS has to deal with flow control (retransmissions, out of order packets, etc.) itself, which needs some attention to get right.  Both client and server handshake state machine are the same.

**Comment by jerome-arzel** [comment]
My use case is a tunnel over UDP with encrypted data frames. Currently the tunnel connection is initiated by a TCP connection, then UDP (vtun-like), I though using a TLS handshake over this initial TCP connection, but I saw in the DTLS RFC that sequence numbers are stored in record frames too for whatever reason.

**Comment by j0sh** [comment]
WebRTC in native OCaml (with DTLS-SRTP [1]) is a use case that interests me. I'd be willing to do some work towards that, if there's interest in merging the DTLS parts here.

[1] https://tools.ietf.org/search/rfc5764

**Comment by hannesm** [comment]
if there is a PR, I'll work on merging it.  I'm currently busy with other things, and no time for DTLS.

**Comment by hannesm** [comment]
3+ years later there still doesn't seem anyone picking up on this, I'm closing this issue -- this does not mean that a DTLS PR wouldn't be welcome.
