### ISSUE TITLE
Any plans for ALPN extension?

### ISSUE THREAD

**Issue by alrev** [mirleft/ocaml-tls#361]
Are there any plans for implementing of ALPN extension? Link to rfc: [rfc](https://tools.ietf.org/html/rfc7301).

**Comment by hannesm** [comment]
I have this planned, but it's not high priority on my task list. Feel free to open a PR.

**Comment by bobbypriambodo** [comment]
Anyone got on it yet? I've been working on this for the last several days and got the basics down. If no one is taking it I'll open a PR hopefully in a few more days.

**Comment by alrev** [comment]
I haven't.

**Comment by bobbypriambodo** [comment]
(WIP) PR opened at #378.
