### ISSUE TITLE
Cannot install due to dependency problem

### ISSUE THREAD

**Issue by pvaibhav** [mirleft/ocaml-tls#370]
I'm trying to install this package via `opam install tls` on an up-to-date macOS system with ocaml 4.06.0 (latest stable as of today).

Unfortunately I run into dependency problem:

```
The following dependencies couldn't be met:
  - tls -> sexplib < 113.01.00
  - tls -> x509 (< 0.3.0 | >= 0.5.0) -> asn1-combinators < 0.2.0
Your request can't be satisfied:
  - asn1-combinators<0.2.0 is not available because your system doesn't comply with ocaml-version >= "4.01.0" & ocaml-version < "4.06.0".
  - sexplib<113.01.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".
```

How to fix? I am guessin at least for the `x509` package, their maintainers should be notified.

**Comment by hannesm** [comment]
release 0.9.0 is now PR'ed to opam-repository https://github.com/ocaml/opam-repository/pull/11104

thanks for your report and patience

**Comment by pvaibhav** [comment]
thanks for your work and happy holidays!
