### ISSUE TITLE
Update to the latest ppx_sexp_conv

### ISSUE THREAD

**Issue by Chris00** [mirleft/ocaml-tls#379]
Please update to the latest version of `ppx_sexp_conv`.  Indeed, trying to install `tls` otherwise requires a lot of downgrades...

**Comment by copy** [comment]
I checked, and `tls` is already compilable with ppx_sexp_conv>=v0.11.1 (it doesn't have the bug that nocrypto suffers from). ppx_sexp_conv>=v0.11.1 also doesn't have a dependency on Base.

**Comment by hannesm** [comment]
yes, we should make a v0.11.1 compatible release of tls and x509, but a precondition is nocrypto being able to cope with v0.11.1 (there's a PR https://github.com/mirleft/ocaml-nocrypto/pull/146).  once that is merged and released, I'll adapt both tls and x509 to deal with ppx_sexp_conv v.0.11.1+.  both need modifications to the META files (similar to nocrypto) to reflect the runtime dependencies.

**Comment by hannesm** [comment]
#381 adds these runtime dependencies (soon to be merged and released)

**Comment by hannesm** [comment]
#381 is merged now, expect a release soon
