### ISSUE TITLE
Need separate tls-mirage package

### ISSUE THREAD

**Issue by talex5** [mirleft/ocaml-tls#400]
At the moment, if you want to get `tls.mirage`, you have to read the opam file to find:

```
"--with-mirage" "%{mirage-flow-lwt+mirage-kv-lwt+mirage-clock+ptime:installed}%" 
```

and then add dependencies in your own opam file on `mirage-flow-lwt, mirage-kv-lwt, mirage-clock, ptime`, even though you might not be using any of them directly. This is fragile and easy to get wrong (see https://github.com/mirage/capnp-rpc/pull/181).

Ideally, tls should be split to provide a separate `tls-mirage` package with the Mirage support, so that people can just depend on that.

**Comment by hannesm** [comment]
done with 0.11.0
