### ISSUE TITLE
High latency on linux with delayed ack enabled

### ISSUE THREAD

**Issue by ansiwen** [mirleft/ocaml-tls#480]
I'm not really sure the issue is ocaml-tls, but it's my best guess for now.

I'm running a Cohttp server with TLS, and I was investigating a suspiciously high latency (~40ms roundtrip) over sub-ms network when sending requests in a persistent TLS connection from an arbitrary https client on Linux. The same did not appear, when doing the requests from MacOS. Looking at the network traces I saw the following issue:

<img width="1206" alt="Bildschirmfoto 2023-10-04 um 14 35 19" src="https://github.com/mirleft/ocaml-tls/assets/7792669/79758040-28c4-4a34-a2ba-e4efa0cba0b6">

The delay between frame 36 and 37 comes from the delayed ack, that is activated by default on Linux. But the question is: why is the server sending only the first fragment of the response and then waiting for the `ACK`? After the `ACK` arrives at the server, it immediately sends the rest of the response (TLS segment 2 and 3) in frame 38. (That there are 3 segments is probably an Cohttp issue, and maybe not even a real issue.)

It does _not_ seem to be the mirage TCP/IP stack, because I can also reproduce it when I build it with the unix socket interface.

If I enable TCP_QUICKACK on the client socket, the issue almost disappears, but sill the request-response needs two roundtrips instead of one, because the server side is waiting for the `ACK` of the first part of the response, before sending the rest.

The first TLS segment contains the HTTP response code line:
<img width="593" alt="Bildschirmfoto 2023-10-04 um 14 36 34" src="https://github.com/mirleft/ocaml-tls/assets/7792669/738e78fc-b030-4f03-8fb9-caf70bc6d76e">

Some versions:
```
ocaml 4.14.0
mirage                  3.10.8
tls-mirage              0.15.3
conduit-mirage          5.0.0
cohttp-mirage           5.0.0
```

**Comment by hannesm** [comment]
Since TLS does no buffering (the `write` / `send_application_data` immediately calls the underlying `FLOW.write`), I'm surprised by this behaviour. Would you mind to sprinkle some log messages around (in TLS and TCP) to figure out which function call is taking so much time? Alternatively, break into a debugger in the Unix version and figure out where the data is?

**Comment by hannesm** [comment]
Thinking a bit more about that, my question is: what is in 36?

My intuition is that the TLS handshake is already established, now in 34 the client requested a resource. The server may do whatever computation is needed, and only when that is finished (webmachine, database fetching, serializing data, ...), a write is called. May it be that the server logic takes 40ms? Again, having log messages with precise timestamps in the tls layer whenever a write is executed (and on the underlying tcp layer, when a write is executed) may be useful to dig deeper.

**Comment by ansiwen** [comment]
Hi @hannesm, thanks for looking at this.

I can produce more logs for sure, but I will first point out some things that I know already now:

Yes, the TLS handshake is established already, it's a persistent TLS connection, in which several HTTP requests are sent sequentially.

Frame 36 is the first of three TLS segments which contains `HTTP/1.1 200 OK\n\r`, that is what I marked in the second screenshot. And then the server is really _waiting_ for the ACK from the client, it's not computing anything. It sends the first TLS segment, waits for the ACK of that first segment, and then sends segment 2 and 3 (that is headers and body in this case) in the next frame (38). I know that, because if I disable the delayed ack on the client side (check out TCP_QUICKACK if you want to know what that is, it was new to me), the ACK is sent immediately, and then also the server responds with the rest of the HTTP response _immediately_ without any waiting time. So what _I_ don't understand is, which layer on the server side is waiting for the ACK from the client for frame 36 before sending the rest of the response is sent? 

In the meantime I checked Cohttp, and the `response` function has a `~flush` argument, that defaults to true and says "If flush is true, then every response chunk will be flushed to the network rather than being buffered.", so that explains why every chunk comes in its own segment. So switching `flush` to `false` will probably circumvent the problem.

Oh, I have an idea! Does the mirage TCP/IP stack also implement the Nagle's Algorithm? That would explain why I see it with both the mirage and the Linux TCP/IP stack, and it is known that the Nagle's Algorithm (disabled with the TCP_NODELAY socket option) and the delayed ACKs don't work well together, because the Nagle's Algorithm _does_ wait for ACKs.

**Comment by hannesm** [comment]
Thanks for your comment.

> Oh, I have an idea! Does the mirage TCP/IP stack also implement the Nagle's Algorithm? That would explain why I see it with both the mirage and the Linux TCP/IP stack, and it is known that the Nagle's Algorithm (disabled with the TCP_NODELAY socket option) and the delayed ACKs don't work well together, because the Nagle's Algorithm does wait for ACKs.

You may want to ask on the mirage/mirage-tcpip repository, or on the MirageOS mailing list about the design and implementation of the mirage-tcpip stack.

**Comment by hannesm** [comment]
To summarize:
1. you can observe the behaviour with mirage-tcpip
2. you can observe the behaviour with a Linux TCP/IP stack
3. you can _not_ observe the behaviour with a Linux TCP/IP stack when you set the TCP_NODELAY socket option (on the server side)
4. you can not observe the behaviour with a client that either is macOS or delayed ACK is disabled (TCP_QUICKACK socket option on the client socket)

Is this a valid summary of the scenarios you tested?

**Comment by ansiwen** [comment]
Yes, 1, 2 and 4 are correct, sorry for my confusing prose style. 🙈
Number 3: that would be my guess now, but I haven't tried yet. (Can I easily set socket options with the mirage socket interface? Then I could quickly confirm that.)

I would now agree, that this is probably _not_ related to the TLS stack. It's rather an issue of the not-disabled Nagle in both TCP stacks. Shall we close this issue and I find a better place for it?

**Comment by ansiwen** [comment]
Here are some logs:

<details><summary>Logs (Click me)</summary>

```
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2527] (state-in
                          ((handshake
                            ((session
                              ((TLS13
                                ((common_session_data13
                                  ((server_random
                                    "9\193r1Q\208\027{\021\152\204%\239\197\190\"Q\023\015\184\189 \199\207C\b\031\143N*\146V")
                                   (client_random
                                    "\2310\224 P;7\196\193\205\143\171\149\155#\005\t\002kG\196\215\025w\188\134\155\255\218\175\211\239")
                                   (peer_certificate_chain ())
                                   (peer_certificate ()) (trust_anchor ())
                                   (received_certificates ())
                                   (own_certificate (certificate))
                                   (own_private_key ("private key"))
                                   (own_name ()) (client_auth false)
                                   (master_secret
                                    "\237\132\226\160Z^\236\016\247\137\129\160\163D\134\025\171\165\178\t_\255J\250\206\138O4\011\170\1389")
                                   (alpn_protocol ())))
                                 (ciphersuite13 AES_128_GCM_SHA256)
                                 (master_secret
                                  ((secret
                                    "\237\132\226\160Z^\236\016\247\137\129\160\163D\134\025\171\165\178\t_\255J\250\206\138O4\011\170\1389")
                                   (cipher AES_128_GCM_SHA256) (hash sha256)))
                                 (resumption_secret "") (state Established)
                                 (resumed false)
                                 (client_app_secret
                                  "\213\199bA\164V~P2Y\226\247\254\011\245u\167\222~\183\002:\175B\157\224\132\206`f\198!")
                                 (server_app_secret
                                  "\229\025$\201b\223\150N\128U\028\237\144Al\003\128\160\011\204\175\199#\142\226\220\193C\2206\211\003")))))
                             (protocol_version TLS_1_3) (early_data_left 0)
                             (machina (Server13 Established13))
                             (config
                              ((ciphers
                                (AES_128_GCM_SHA256 AES_256_GCM_SHA384
                                 CHACHA20_POLY1305_SHA256 AES_128_CCM_SHA256
                                 ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                                 ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                                 ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256))
                               (protocol_versions (TLS_1_2 TLS_1_3))
                               (signature_algorithms
                                (ECDSA_SECP256R1_SHA256
                                 ECDSA_SECP384R1_SHA384
                                 ECDSA_SECP521R1_SHA512 ED25519
                                 RSA_PSS_RSAENC_SHA256 RSA_PSS_RSAENC_SHA384
                                 RSA_PSS_RSAENC_SHA512 RSA_PKCS1_SHA256
                                 RSA_PKCS1_SHA384 RSA_PKCS1_SHA512
                                 RSA_PKCS1_SHA224 ECDSA_SECP256R1_SHA1
                                 RSA_PKCS1_SHA1 RSA_PKCS1_MD5))
                               (use_reneg false) (authenticator ())
                               (peer_name ())
                               (own_certificates
                                (Single ((certificate) "private key")))
                               (acceptable_cas ())
                               (session_cache SESSION_CACHE)
                               (ticket_cache TICKET_CACHE)
                               (cached_session ()) (cached_ticket ())
                               (alpn_protocols ())
                               (groups
                                (X25519 P384 P256 P521 FFDHE2048 FFDHE3072
                                 FFDHE4096 FFDHE6144 FFDHE8192))
                               (zero_rtt 0) (ip ())))
                             (hs_fragment "")))
                           (decryptor
                            (((sequence 74) (cipher_st <aead-state>))))
                           (encryptor
                            (((sequence 222) (cipher_st <aead-state>))))
                           (fragment "")))

17 03 03 00 69 5b 37 bf  63 e1 ec 24 bc fe ec 91
ed fc 1b 49 c0 2d a8 8c  5b 1d 0e 06 4d 20 1e 63
a1 5e f5 99 41 7f 95 c1  8e 2b 1b ba 42 b0 41 2a
6a 38 1e 49 58 c2 35 12  81 f2 35 5f 9d e6 37 96
e3 77 9d b2 83 2e c2 d2  39 9b b1 f7 07 6c 20 b3
33 39 c1 cd 78 a9 40 38  6c e4 01 22 3f 3f a3 37
75 44 fb a5 de b0 03 06  e9 ce da d8 cb 30
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2528] (wire-in "")
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2529] (record-in
                          (((content_type APPLICATION_DATA)
                            (version TLS_1_2))
                           "[7\191c\225\236$\188\254\236\145\237\252\027I\192-\168\140[\029\014\006M \030c\161^\245\153A\127\149\193\142+\027\186B\176A*j8\030IX\1945\018\129\2425_\157\2307\150\227w\157\178\131.\194\2109\155\177\247\007l \17939\193\205x\169@8l\228\001\"??\1637uD\251\165\222\176\003\006\233\206\218\216\2030"))
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2530] (frame-in
                          (APPLICATION_DATA
                            "GET /api/v1/info HTTP/1.1\r\
                           \nHost: 127.0.0.1:8443\r\
                           \nUser-Agent: curl/8.0.1\r\
                           \nAccept: */*\r\
                           \n\r\
                           \n"))

47 45 54 20 2f 61 70 69  2f 76 31 2f 69 6e 66 6f
20 48 54 54 50 2f 31 2e  31 0d 0a 48 6f 73 74 3a
20 31 32 37 2e 30 2e 30  2e 31 3a 38 34 34 33 0d
0a 55 73 65 72 2d 41 67  65 6e 74 3a 20 63 75 72
6c 2f 38 2e 30 2e 31 0d  0a 41 63 63 65 70 74 3a
20 2a 2f 2a 0d 0a 0d 0a
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2531] (application-data-in "")
2023-10-05 16:49:43 -00:00: DBG [cohttp.lwt.server] [2532] Handle request: ((headers ((Host 127.0.0.1:8443) (User-Agent curl/8.0.1) (Accept */*)))
 (meth GET) (scheme ()) (resource /api/v1/info) (version HTTP_1_1)
 (encoding Unknown)).
2023-10-05 16:49:43 -00:00: DBG [http.access] [2533] IP of client is 192.168.1.100
2023-10-05 16:49:43 -00:00: DBG [http.access] [2534] [6] serving //127.0.0.1:8443/api/v1/info.
2023-10-05 16:49:43 -00:00: INF [http.access] [2535] request GET /api/v1/info
2023-10-05 16:49:43 -00:00: DBG [http.access] [2536] request headers Host: 127.0.0.1:8443
User-Agent: curl/8.0.1
Accept: */*


2023-10-05 16:49:43 -00:00: INF [http.access] [2537] response 200 response time 169us
2023-10-05 16:49:43 -00:00: DBG [http.access] [2538] GET /api/v1/info path: v3b13, v3b12, v3b11, v3b10, v3b9, v3b8, v3b7, v3b6, v3b5, v3b4, v3b3, v3c3, v3c4, v3d4, v3e5, v3f6, v3g7, v3g8, v3h10, v3i12, v3l13, v3m16, v3n16, v3o16, v3o18

48 54 54 50 2f 31 2e 31  20 32 30 30 20 4f 4b 0d
0a
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2539] (application-data-out "")
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2540] (frame-out (APPLICATION_DATA "HTTP/1.1 200 OK\r\n"))
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2541] (record-out
                          (APPLICATION_DATA
                            "\007\029\217\154(\208\029\167\149\208\020\\\210\176?\211\217~\004\159\229\161\221\202\006@7T\155/qf\
                           \n\182"))

17 03 03 00 22 07 1d d9  9a 28 d0 1d a7 95 d0 14
5c d2 b0 3f d3 d9 7e 04  9f e5 a1 dd ca 06 40 37
54 9b 2f 71 66 0a b6
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2542] (wire-out "")
2023-10-05 16:49:43 -00:00: DBG [ipv4] [2543] ip write: mtu is 1500, hdr_len is 20, size 59 payload len 0, needed_bytes 79

43 6f 6e 74 65 6e 74 2d  54 79 70 65 3a 20 61 70
70 6c 69 63 61 74 69 6f  6e 2f 6a 73 6f 6e 0d 0a
76 61 72 79 3a 20 41 63  63 65 70 74 2c 20 41 63
63 65 70 74 2d 45 6e 63  6f 64 69 6e 67 2c 20 41
63 63 65 70 74 2d 43 68  61 72 73 65 74 2c 20 41
63 63 65 70 74 2d 4c 61  6e 67 75 61 67 65 0d 0a
45 54 61 67 3a 20 22 37  62 61 62 36 32 35 31 30
65 30 35 63 33 33 32 37  33 35 36 32 34 62 63 37
61 35 38 35 61 33 30 22  0d 0a 44 61 74 65 3a 20
54 68 75 2c 20 30 35 20  4f 63 74 20 32 30 32 33
20 31 36 3a 34 39 3a 34  33 20 47 4d 54 0d 0a 63
6f 6e 74 65 6e 74 2d 6c  65 6e 67 74 68 3a 20 34
35 0d 0a 0d 0a
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2544] (application-data-out "")
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2545] (frame-out
                          (APPLICATION_DATA
                            "Content-Type: application/json\r\
                           \nvary: Accept, Accept-Encoding, Accept-Charset, Accept-Language\r\
                           \nETag: \"7bab62510e05c332735624bc7a585a30\"\r\
                           \nDate: Thu, 05 Oct 2023 16:49:43 GMT\r\
                           \ncontent-length: 45\r\
                           \n\r\
                           \n"))
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2546] (record-out
                          (APPLICATION_DATA
                           "=\156\148\169Y>\237\205\173}\172h\199!\193!\204\136'\1407&C\133\146\006I\216\253>\168\026\229\226\2060\218\232\168\224\135:?\186\222\184\179?6\153FD+x\149\140\147\1841\201E\148\252\133A\189\022\140\022\148\224H\184\255F\030\254\215&]\140\174fXy\018E\248\176\147\133&\138\0175\202\204\\7\197\195\129\140\201\127\129\247=\192\171\201\243\232\154\171\234\222\191\191\165\197\160\b(\0225\229\218<\162~\152\197$\137\004\201j\159DC\014C<\236\2076\252\158(~\185\021r\014\140\023\139l&\004\tL!\203\252}u\136\143\185\196\238V\147-Wi~\234\177\175\172\222\172\203\029\158f\214r\012\234\184\181\011\147\249\003\166|m\1363\138HK\202R\028\245\218-\139"))

17 03 03 00 d6 3d 9c 94  a9 59 3e ed cd ad 7d ac
68 c7 21 c1 21 cc 88 27  8c 37 26 43 85 92 06 49
d8 fd 3e a8 1a e5 e2 ce  30 da e8 a8 e0 87 3a 3f
ba de b8 b3 3f 36 99 46  44 2b 78 95 8c 93 b8 31
c9 45 94 fc 85 41 bd 16  8c 16 94 e0 48 b8 ff 46
1e fe d7 26 5d 8c ae 66  58 79 12 45 f8 b0 93 85
26 8a 11 35 ca cc 5c 37  c5 c3 81 8c c9 7f 81 f7
3d c0 ab c9 f3 e8 9a ab  ea de bf bf a5 c5 a0 08
28 16 35 e5 da 3c a2 7e  98 c5 24 89 04 c9 6a 9f
44 43 0e 43 3c ec cf 36  fc 9e 28 7e b9 15 72 0e
8c 17 8b 6c 26 04 09 4c  21 cb fc 7d 75 88 8f b9
c4 ee 56 93 2d 57 69 7e  ea b1 af ac de ac cb 1d
9e 66 d6 72 0c ea b8 b5  0b 93 f9 03 a6 7c 6d 88
33 8a 48 4b ca 52 1c f5  da 2d 8b
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2547] (wire-out "")
2023-10-05 16:49:43 -00:00: DBG [ipv4] [2548] ip write: mtu is 1500, hdr_len is 20, size 239 payload len 0, needed_bytes 259

7b 22 76 65 6e 64 6f 72  22 3a 22 4e 69 74 72 6f
6b 65 79 20 47 6d 62 48  22 2c 22 70 72 6f 64 75
63 74 22 3a 22 4e 65 74  48 53 4d 22 7d
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2549] (application-data-out "")
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2550] (frame-out
                          (APPLICATION_DATA
                           "{\"vendor\":\"Nitrokey GmbH\",\"product\":\"NetHSM\"}"))
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2551] (record-out
                          (APPLICATION_DATA
                            "*\230\000\222\157\233{d]\165Qh\145\220\146\135\017<~\149^\216\228\1745B\164\173\198E\001\
                           \n\r\138\130\133I{R\140\011\250\205]9\180\157(\020\191\174\199\150\224y\139\016\181\1343\155\179"))

17 03 03 00 3e 2a e6 00  de 9d e9 7b 64 5d a5 51
68 91 dc 92 87 11 3c 7e  95 5e d8 e4 ae 35 42 a4
ad c6 45 01 0a 0d 8a 82  85 49 7b 52 8c 0b fa cd
5d 39 b4 9d 28 14 bf ae  c7 96 e0 79 8b 10 b5 86
33 9b b3
2023-10-05 16:49:43 -00:00: DBG [tls.tracing] [2552] (wire-out "")
2023-10-05 16:49:43 -00:00: DBG [ipv4] [2553] ip write: mtu is 1500, hdr_len is 20, size 87 payload len 0, needed_bytes 107
2023-10-05 16:49:43 -00:00: DBG [ipv4] [2554] ip write: mtu is 1500, hdr_len is 20, size 20 payload len 0, needed_bytes 40
2023-10-05 16:49:43 -00:00: DBG [tcp.window] [2555] sequence validation: seq=2661922257 range=2661922257[262140] res=true
2023-10-05 16:49:43 -00:00: DBG [tcp.state] [2556] Established  - Recv_ack(935056530) -> Established
2023-10-05 16:49:43 -00:00: DBG [tcp.window] [2557] sequence validation: seq=2661922257 range=2661922257[262140] res=true
2023-10-05 16:49:43 -00:00: DBG [tcp.state] [2558] Established  - Recv_ack(935056597) -> Established

```

</details>

**Comment by hannesm** [comment]
Since, as you mentioned, this has something to do with "cohttp" and "TCP", I'll close this issue here.

**Comment by hannesm** [comment]
What I'd propose to proceed with, considering that clearly TCP_NODELAY is a decent socket option (as your issue has shown). Using different functions (write / write_nodelay) does not compose well (i.e. the TLS stack won't offer such a multitude of functions that are mostly the same, only calling some other function on the lower level).

Thus, maybe in the TCP interface we need a way to set socket options (or flow options) on a flow. Then, you could set the TCP_NODELAY before passing it to TLS, and the TCP stack could decide to use write / write_nodelay depending on the socket options configured.

So, to me the solution would be (I have not looked into cohttp at all):
- propose a PR to mirage-tcpip (src/core/tcp.ml{i}) to set socket options (for now, NODELAY)
- propose a PR to mirage-tcpip (src/tcp) to implement that interface change
- figure out whether there are any users of write_nodelay, deprecate or remove it from the interface
- figure out a way to set NODELAY in cohttp/conduit (i.e. either access the flow on the application side, or pass in some argument somewhere)

(take it or leave it, it is only what I'd propose -- feel free to find and propose other solutions)

**Comment by ansiwen** [comment]
@hannesm thanks for the guidelines. Sounds good.
