### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by toots** [mirleft/ocaml-tls#490]
Hi there!

Not really an issue so feel free to close but for future reference, it would be nice to do a bigger bump when breaking the API. Most users would not expect upgrading from `0.17.3` to `0.17.4` to break existing code.

Thanks!

**Comment by toots** [comment]
Also, a 6-tuple would probably be more user-friendly implemented as a record 🙂

**Comment by toots** [comment]
Also, a 4-tuple would be more user friend implemented as a record.. 🙂

**Comment by hannesm** [comment]
Thanks for your remark. Indeed OCaml-TLS follows semantic versioning. Take a look into https://semver.org/#spec-item-4 if you're interested why there's nothing wrong with it.

On the broader side of things, the next release will be a 1.0. If you have constructive API feedback, please open an issue or PR.

**Comment by hannesm** [comment]
Oh, and thanks for your report, and sorry that this affects you. I will be more strict in terms of semantic versioning in the future.

**Comment by toots** [comment]
Thanks!
