### ISSUE TITLE
Unhandled alert

### ISSUE THREAD

**Issue by reynir** [mirleft/ocaml-tls#491]
While testing https://github.com/hannesm/ocaml-tls/tree/no-cstruct I discovered that openssl s_client sends an alert in a place where we don't handle it:
https://github.com/mirleft/ocaml-tls/blob/fc78dd87b26600ed977eb2f18aab4e86d43dfb73/lib/engine.ml#L309

The alert in question is fatal bad record mac. I attempted the following to get better error reporting, but I suspect it is not quite right.

```OCaml
     | Packet.ALERT ->
       let* alert = map_reader_error (Reader.parse_alert buf) in
       (match alert with
        | _, BAD_RECORD_MAC -> Error (`Fatal `MACMismatch)
        | _, _ -> Error (`Fatal `InvalidMessage))
```

**Comment by hannesm** [comment]
Thanks for your report, I added a nicer error message in e4e9c95
