### ISSUE TITLE
RC4 security in TLS

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-tls#8]
problem: some bytes can be recovered

solution: throw RC4 away and switch to CBC

references
- http://www.isg.rhul.ac.uk/tls/index.html

**Comment by g2p** [comment]
Is RC4 really disabled, or just not advertised as per the commit message?
The RFC says RC4 must never be negotiated ([Firefox roadmap](https://community.qualys.com/thread/14736)): https://tools.ietf.org/html/rfc7465
Otherwise an active attacker would drop a connection and force the use of RC4.

**Comment by hannesm** [comment]
in the (default config)[https://github.com/mirleft/ocaml-tls/blob/master/lib/config.ml#L36] in master, RC4 is disabled -- it can not be negotiated. You can still configure OCaml-TLS to use RC4. The 0.3.0 release still advertises RC4 by default (but there'll be a 0.4.0 really soon now)!
As example, https://ownme.ipredator.se will never negotiate RC4 (while https://tls.openmirage.org will).
